
FROM tomcat:9.0-alpine
# FROM tomcat:8.5-alpine
# FROM tomcat:8.0-alpine

ARG CONFIG_FILE
ARG WAR_FILE

COPY ${CONFIG_FILE} /usr/local/tomcat/conf/server.xml
COPY ${WAR_FILE} /usr/local/tomcat/webapps/

EXPOSE 8080
CMD ["catalina.sh", "run"]
